# Generated by Django 5.2.4 on 2026-07-06 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLessonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chưa đúng định dạng Việt Nam.', regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('booking_type', models.CharField(choices=[('trial', 'Học thử'), ('placement', 'Test đầu vào')], max_length=20, verbose_name='Nhu cầu')),
                ('preferred_date', models.DateField(verbose_name='Ngày mong muốn')),
                ('preferred_slot', models.CharField(max_length=80, verbose_name='Khung giờ')),
                ('current_level', models.CharField(blank=True, max_length=120, verbose_name='Trình độ hiện tại')),
                ('goal', models.TextField(blank=True, verbose_name='Mục tiêu học tập')),
                ('status', models.CharField(choices=[('new', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã tham gia'), ('cancelled', 'Đã hủy')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt lịch')),
            ],
            options={
                'verbose_name': 'Lịch học thử / test',
                'verbose_name_plural': 'Lịch học thử / test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chưa đúng định dạng Việt Nam.', regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('current_level', models.CharField(blank=True, max_length=120, verbose_name='Trình độ hiện tại')),
                ('preferred_time', models.CharField(blank=True, max_length=180, verbose_name='Thời gian thuận tiện')),
                ('message', models.TextField(blank=True, verbose_name='Lời nhắn')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('enrolled', 'Đã nhập học'), ('closed', 'Đã đóng')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Khóa học quan tâm')),
            ],
            options={
                'verbose_name': 'Đăng ký tư vấn',
                'verbose_name_plural': 'Đăng ký tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
