# Generated by Django 5.2.4 on 2026-07-06 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Tiêu đề')),
                ('subtitle', models.TextField(verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Ảnh banner')),
                ('button_text', models.CharField(default='Đăng ký học thử', max_length=50, verbose_name='Nhãn nút')),
                ('button_url', models.CharField(default='/dat-lich-hoc-thu/', max_length=255, verbose_name='Đường dẫn nút')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
            ],
            options={
                'verbose_name': 'Banner trang chủ',
                'verbose_name_plural': 'Banner trang chủ',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=180, verbose_name='Tên trung tâm')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('hotline', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chưa đúng định dạng Việt Nam.', regex='^(0|\\+84)[0-9]{9,10}$')], verbose_name='Hotline')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('zalo_url', models.URLField(verbose_name='Zalo')),
                ('facebook_url', models.URLField(verbose_name='Facebook')),
                ('messenger_url', models.URLField(verbose_name='Messenger')),
                ('map_embed_url', models.URLField(max_length=1000, verbose_name='Link nhúng Google Maps')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Giờ làm việc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp',
                'verbose_name_plural': 'Câu hỏi thường gặp',
                'ordering': ['order', 'id'],
            },
        ),
    ]
