# Generated by Django 5.2.15 on 2026-07-21 09:22

import config.image_pipeline
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_active_banner_media_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/', validators=[config.image_pipeline.validate_web_image], verbose_name='Ảnh banner'),
        ),
    ]
