# Generated by Django 5.2.4 on 2026-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Đường dẫn')),
                ('excerpt', models.CharField(max_length=320, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Ảnh đại diện')),
                ('author_name', models.CharField(default='Ban học thuật', max_length=100, verbose_name='Tác giả')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Tiêu đề')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Hình ảnh')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], default='image', max_length=10, verbose_name='Loại nội dung')),
                ('video_url', models.URLField(blank=True, verbose_name='Link video')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Chú thích')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Ngày diễn ra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Thư viện ảnh / video',
                'verbose_name_plural': 'Thư viện ảnh / video',
                'ordering': ['order', '-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120, verbose_name='Tên học viên')),
                ('course_name', models.CharField(max_length=180, verbose_name='Khóa học / thành tích')),
                ('content', models.TextField(verbose_name='Chia sẻ')),
                ('score', models.CharField(blank=True, max_length=80, verbose_name='Điểm HSK')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Ảnh học viên')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Đánh giá')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Feedback học viên',
                'verbose_name_plural': 'Feedback học viên',
                'ordering': ['order', '-id'],
            },
        ),
    ]
