# Generated by Django 5.2.15 on 2026-07-21 09:22

import config.image_pipeline
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_restore_production_media_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog/', validators=[config.image_pipeline.validate_web_image], verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/', validators=[config.image_pipeline.validate_web_image], verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='testimonials/', validators=[config.image_pipeline.validate_web_image], verbose_name='Ảnh học viên'),
        ),
    ]
