# Generated by Django 5.2.4 on 2026-07-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Tên khóa học')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('level', models.CharField(max_length=80, verbose_name='Trình độ')),
                ('short_description', models.CharField(max_length=255, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Nội dung chi tiết')),
                ('duration', models.CharField(max_length=100, verbose_name='Thời lượng')),
                ('sessions', models.PositiveSmallIntegerField(verbose_name='Số buổi')),
                ('class_size', models.CharField(default='8–12 học viên', max_length=80, verbose_name='Sĩ số')),
                ('tuition', models.PositiveIntegerField(verbose_name='Học phí (VNĐ)')),
                ('target_students', models.TextField(verbose_name='Đối tượng học')),
                ('outcomes', models.TextField(help_text='Mỗi kết quả một dòng.', verbose_name='Kết quả đầu ra')),
                ('syllabus', models.TextField(help_text='Mỗi chặng một dòng.', verbose_name='Lộ trình học')),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Ảnh khóa học')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang tuyển sinh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30, unique=True, verbose_name='Mã lớp')),
                ('start_date', models.DateField(verbose_name='Ngày khai giảng')),
                ('schedule_text', models.CharField(max_length=180, verbose_name='Lịch học')),
                ('format', models.CharField(choices=[('offline', 'Học trực tiếp'), ('online', 'Học online'), ('hybrid', 'Linh hoạt')], max_length=20, verbose_name='Hình thức')),
                ('seats_left', models.PositiveSmallIntegerField(default=10, verbose_name='Chỗ còn lại')),
                ('teacher', models.CharField(max_length=120, verbose_name='Giảng viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang nhận đăng ký')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Lịch khai giảng',
                'verbose_name_plural': 'Lịch khai giảng',
                'ordering': ['start_date', 'course__order'],
            },
        ),
    ]
