from django.db import migrations


COURSES = [
    {
        "title": "Tiếng Trung nhập môn cho người mới",
        "slug": "tieng-trung-nhap-mon-cho-nguoi-moi",
        "level": "Người mới",
        "short_description": "Giáo trình Tiếng Việt 123 Q1 cho người mới bắt đầu.",
        "description": "Lộ trình trình độ A theo giáo trình Tiếng Việt 123 Q1, tập trung giới thiệu bản thân, phân biệt bảng chữ cái, đếm số, mua sắm, hỏi đường, thời tiết, thuê nhà và giao tiếp khách sạn.",
        "duration": "40 buổi",
        "sessions": 40,
        "class_size": "8–12 học viên",
        "tuition": 4000000,
        "target_students": "Người chưa từng học tiếng Trung hoặc đã tự học nhưng mất gốc.\nHọc sinh, sinh viên và người đi làm cần nền tảng chắc trước khi học HSK.",
        "outcomes": "Đọc đúng pinyin và phân biệt bốn thanh điệu\nViết được các nét và bộ thủ cơ bản\nGiao tiếp giới thiệu, hỏi đường, mua sắm và lịch hẹn\nSẵn sàng bước vào lộ trình HSK 2",
        "syllabus": "Phát âm pinyin, khẩu hình và quy tắc biến điệu\n80 chữ Hán nền tảng và phương pháp ghi nhớ\nMẫu câu giao tiếp theo chủ đề đời sống\nÔn tập, hội thoại và kiểm tra cuối khóa",
        "is_featured": True,
        "order": 1,
    },
    {
        "title": "Tiếng Trung YCT 1 cho trẻ em",
        "slug": "tieng-trung-yct-1-cho-tre-em",
        "level": "YCT",
        "short_description": "Khóa YCT 1 gồm 40 buổi, xây nền tiếng Trung vui và dễ hiểu cho trẻ.",
        "description": "Chương trình dùng giáo trình YCT 1, giúp học viên nhỏ tuổi làm quen phát âm, từ vựng và mẫu câu cơ bản qua hoạt động tương tác.",
        "duration": "40 buổi",
        "sessions": 40,
        "class_size": "6–10 học viên",
        "tuition": 3200000,
        "target_students": "Học sinh nhỏ tuổi mới bắt đầu học tiếng Trung.\nPhụ huynh muốn con có lộ trình YCT rõ ràng.",
        "outcomes": "Nhận biết âm và từ vựng cơ bản\nNói các câu chào hỏi, giới thiệu đơn giản\nHình thành thói quen học tiếng Trung tích cực",
        "syllabus": "Làm quen phát âm và lớp học\nTừ vựng YCT 1 theo chủ đề gần gũi\nLuyện nghe nói qua trò chơi và hội thoại\nÔn tập cuối khóa",
        "is_featured": True,
        "order": 2,
    },
    {
        "title": "Tiếng Trung YCT 2 cho trẻ em",
        "slug": "tieng-trung-yct-2-cho-tre-em",
        "level": "YCT",
        "short_description": "Khóa YCT 2 gồm 50 buổi, mở rộng vốn từ và phản xạ giao tiếp.",
        "description": "Chương trình dùng giáo trình YCT 2, nối tiếp nền YCT 1 và tăng dần khả năng nghe nói theo tình huống.",
        "duration": "50 buổi",
        "sessions": 50,
        "class_size": "6–10 học viên",
        "tuition": 4000000,
        "target_students": "Học sinh đã học YCT 1 hoặc có nền tiếng Trung sơ cấp.\nTrẻ cần học đều để chuẩn bị kiểm tra YCT.",
        "outcomes": "Mở rộng từ vựng theo chủ đề gia đình, trường học và sinh hoạt\nNghe hiểu câu ngắn quen thuộc\nTự tin trả lời các mẫu câu đơn giản",
        "syllabus": "Ôn nền YCT 1\nTừ vựng và mẫu câu YCT 2\nLuyện nghe nói theo cặp\nÔn tập và kiểm tra cuối khóa",
        "is_featured": False,
        "order": 3,
    },
    {
        "title": "Tiếng Trung YCT 3 cho trẻ em",
        "slug": "tieng-trung-yct-3-cho-tre-em",
        "level": "YCT",
        "short_description": "Khóa YCT 3 gồm 60 buổi, củng cố đọc hiểu và giao tiếp theo chủ đề.",
        "description": "Chương trình dùng giáo trình YCT 3, giúp học viên nhỏ tuổi nâng độ dài câu, đọc hiểu đoạn ngắn và chuẩn bị tốt hơn cho lộ trình HSK sau này.",
        "duration": "60 buổi",
        "sessions": 60,
        "class_size": "6–10 học viên",
        "tuition": 4800000,
        "target_students": "Học sinh đã hoàn thành YCT 2 hoặc có trình độ tương đương.\nTrẻ cần lộ trình dài hơn để duy trì tiếng Trung đều đặn.",
        "outcomes": "Đọc hiểu đoạn ngắn phù hợp lứa tuổi\nNói được câu dài hơn theo chủ đề quen thuộc\nSẵn sàng chuyển tiếp sang YCT cao hơn hoặc HSK sơ cấp",
        "syllabus": "Ôn tập YCT 2\nTừ vựng và ngữ pháp YCT 3\nLuyện đọc hiểu và hội thoại\nThi thử, chữa lỗi và tổng kết",
        "is_featured": False,
        "order": 4,
    },
    {
        "title": "Tiếng Trung 123 - Trình độ B",
        "slug": "tieng-trung-123-trinh-do-b",
        "level": "Người mới",
        "short_description": "Giáo trình Tiếng Việt 123 Q2, học tiếp hội thoại và chủ đề đời sống.",
        "description": "Lộ trình trình độ B theo giáo trình Tiếng Việt 123 Q2, tập trung hội thoại về mua sắm, ẩm thực, giải trí, sức khỏe, học tập, nghề nghiệp, dịch vụ và an ninh trật tự.",
        "duration": "30 buổi",
        "sessions": 30,
        "class_size": "8–12 học viên",
        "tuition": 3000000,
        "target_students": "Học viên đã hoàn thành trình độ A hoặc nắm được phát âm và giao tiếp sơ cấp.\nNgười muốn tăng phản xạ hội thoại đời sống.",
        "outcomes": "Mở rộng vốn từ giao tiếp đời sống\nHỏi đáp tự tin hơn trong các tình huống quen thuộc\nCó nền để chuyển sang lộ trình HSK sơ cấp",
        "syllabus": "Ôn nhanh nền trình độ A\nChủ đề mua sắm, ăn uống và giải trí\nChủ đề sức khỏe, học tập, nghề nghiệp và dịch vụ\nLuyện hội thoại và kiểm tra cuối khóa",
        "is_featured": False,
        "order": 5,
    },
    {
        "title": "Luyện thi HSK 1",
        "slug": "luyen-thi-hsk-1",
        "level": "HSK 1",
        "short_description": "HSK Standard Course 1 gồm 24 buổi cho nền sơ cấp.",
        "description": "Khóa HSK 1 bám giáo trình HSK Standard Course 1, giúp học viên hệ thống từ vựng, cấu trúc câu và kỹ năng nghe đọc nền tảng.",
        "duration": "24 buổi",
        "sessions": 24,
        "class_size": "8–12 học viên",
        "tuition": 4800000,
        "target_students": "Người mới đã có nền phát âm cơ bản.\nHọc viên muốn bắt đầu lộ trình thi HSK chính quy.",
        "outcomes": "Nắm chắc từ vựng và mẫu câu HSK 1\nNghe hiểu hội thoại rất ngắn\nĐọc hiểu câu đơn và làm quen định dạng đề",
        "syllabus": "Từ vựng HSK 1\nMẫu câu và ngữ pháp nền\nLuyện nghe đọc theo bài\nÔn tập và thi thử",
        "is_featured": False,
        "order": 6,
    },
    {
        "title": "Luyện thi HSK 2 nền tảng",
        "slug": "luyen-thi-hsk-2-nen-tang",
        "level": "HSK 2",
        "short_description": "HSK Standard Course 2 gồm 30 buổi, luyện nghe đọc sơ cấp.",
        "description": "Khóa học bám giáo trình HSK Standard Course 2, dành cho học viên đã có nền HSK 1 hoặc tương đương và muốn tăng tốc lên HSK 2.",
        "duration": "30 buổi",
        "sessions": 30,
        "class_size": "8–12 học viên",
        "tuition": 6000000,
        "target_students": "Học viên đã hoàn thành nhập môn hoặc có vốn từ cơ bản.\nNgười cần chứng chỉ HSK 2 để hoàn thiện hồ sơ học tập.",
        "outcomes": "Nắm chắc khoảng 500 từ theo khung HSK mới\nNghe hiểu hội thoại ngắn với tốc độ vừa\nĐọc hiểu thông báo và đoạn văn cơ bản\nLàm quen cấu trúc đề thi HSK",
        "syllabus": "Ôn phát âm và kiểm tra vốn từ đầu vào\nTừ vựng, ngữ pháp và nghe theo chủ đề\nĐọc hiểu, sắp xếp câu và phản xạ hội thoại\nLuyện đề tổng hợp và chữa lỗi cá nhân",
        "is_featured": True,
        "order": 7,
    },
    {
        "title": "Chinh phục HSK 3",
        "slug": "chinh-phuc-hsk-3",
        "level": "HSK 3",
        "short_description": "HSK Standard Course 3 gồm 36 buổi, tăng tốc nghe đọc.",
        "description": "Lộ trình HSK 3 theo HSK Standard Course 3, cân bằng giữa ngôn ngữ ứng dụng và kỹ năng làm bài thi.",
        "duration": "36 buổi",
        "sessions": 36,
        "class_size": "8–12 học viên",
        "tuition": 7200000,
        "target_students": "Học viên đã hoàn thành HSK 2 hoặc đạt bài test đầu vào tương đương.\nNgười cần HSK 3 cho học tập, việc làm hoặc chuẩn bị du học.",
        "outcomes": "Sử dụng khoảng 1.000 từ trong chủ đề quen thuộc\nNghe bắt ý chính và thông tin chi tiết\nĐọc hiểu đoạn văn có liên kết\nHoàn thành đề HSK 3 đúng thời gian",
        "syllabus": "Hệ thống lại nền HSK 2 và lấp lỗ hổng\nPhát triển từ vựng, ngữ pháp theo 12 chủ đề\nLuyện nghe đọc theo dạng câu hỏi\nBa vòng luyện đề và thi thử cuối khóa",
        "is_featured": True,
        "order": 8,
    },
    {
        "title": "Luyện thi HSK 4 tăng tốc",
        "slug": "luyen-thi-hsk-4-tang-toc",
        "level": "HSK 4",
        "short_description": "HSK Standard Course 4 trọn quyển thượng và hạ.",
        "description": "Khóa HSK 4 gồm quyển thượng 22 buổi và quyển hạ 22 buổi. Nội dung tập trung vốn từ trung cấp, đọc hiểu tốc độ cao, viết câu chính xác và luyện đề có phân tích lỗi.",
        "duration": "44 buổi",
        "sessions": 44,
        "class_size": "6–10 học viên",
        "tuition": 8800000,
        "target_students": "Người đã đạt HSK 3 hoặc tương đương.\nHọc viên cần HSK 4 để xét tốt nghiệp, xin học bổng hoặc ứng tuyển doanh nghiệp Trung Quốc.",
        "outcomes": "Làm chủ khoảng 2.000 từ vựng theo khung mới\nNắm chiến thuật nghe và đọc giới hạn thời gian\nViết câu đúng trật tự và ngữ pháp\nĐạt mục tiêu 220+ qua các lần thi thử",
        "syllabus": "Quyển thượng: 22 buổi - 4.400.000đ\nQuyển hạ: 22 buổi - 4.400.000đ\nLuyện từng dạng nghe, đọc và viết\nThi thử, thống kê lỗi và tăng tốc",
        "is_featured": True,
        "order": 9,
    },
    {
        "title": "Ôn thi HSK 5 chuyên sâu",
        "slug": "on-thi-hsk-5-chuyen-sau",
        "level": "HSK 5",
        "short_description": "HSK Standard Course 5 trọn quyển thượng và hạ.",
        "description": "Chương trình HSK 5 gồm quyển thượng 30 buổi và quyển hạ 30 buổi, dành cho học viên cần điểm HSK 5 phục vụ du học, học bổng hoặc công việc chuyên môn.",
        "duration": "60 buổi",
        "sessions": 60,
        "class_size": "6–8 học viên",
        "tuition": 18000000,
        "target_students": "Học viên có nền HSK 4 vững và sẵn sàng dành tối thiểu 8 giờ tự học mỗi tuần.",
        "outcomes": "Mở rộng vốn từ trung cao cấp theo chủ đề\nĐọc nhanh bài dài và xác định lập luận\nViết đoạn văn mạch lạc từ tranh và từ khóa\nKiểm soát thời gian ở đề thi HSK 5",
        "syllabus": "Quyển thượng: 30 buổi - 9.000.000đ\nQuyển hạ: 30 buổi - 9.000.000đ\nĐọc dài, nghe nhanh và kỹ thuật ghi chú\nLuyện viết, thi thử và chiến lược phòng thi",
        "is_featured": False,
        "order": 11,
    },
    {
        "title": "Luyện thi HSK 6 chuyên sâu",
        "slug": "luyen-thi-hsk-6-chuyen-sau",
        "level": "HSK 6",
        "short_description": "HSK Standard Course 6 gồm 4 giai đoạn chuyên sâu.",
        "description": "Lộ trình HSK 6 chia thành bốn giai đoạn: đọc hiểu học thuật, nghe nâng cao, viết học thuật, luyện đề và đánh giá toàn diện.",
        "duration": "70 buổi",
        "sessions": 70,
        "class_size": "6–8 học viên",
        "tuition": 21000000,
        "target_students": "Học viên đã hoàn thành HSK 5 hoặc có nền trung cao cấp vững.\nNgười cần HSK 6 cho học thuật, công việc hoặc hồ sơ du học.",
        "outcomes": "Đọc hiểu văn bản học thuật dài\nNghe bắt ý và ghi chú ở tốc độ cao\nViết bài có cấu trúc và lập luận rõ\nLàm đề HSK 6 theo chiến thuật cá nhân",
        "syllabus": "Giai đoạn 1: đọc hiểu học thuật - 20 buổi - 6.000.000đ\nGiai đoạn 2: nghe nâng cao - 15 buổi - 4.500.000đ\nGiai đoạn 3: viết học thuật - 15 buổi - 4.500.000đ\nGiai đoạn 4: luyện đề và đánh giá toàn diện - 20 buổi - 6.000.000đ",
        "is_featured": False,
        "order": 12,
    },
]


def upsert_official_courses(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for data in COURSES:
        Course.objects.update_or_create(
            title=data["title"],
            defaults={**data, "is_active": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(upsert_official_courses, noop_reverse),
    ]
