# Generated by Django 5.2.15 on 2026-07-21 09:22

import config.image_pipeline
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_clarify_hsk4_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/', validators=[config.image_pipeline.validate_web_image], verbose_name='Ảnh khóa học'),
        ),
    ]
